spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.username=root
spring.datasource.password=Dontforget@2647

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
